baseURL = 'https://urbandavebe.github.io/'
languageCode = 'en-us'
title = 'some random docs'
theme = 'hugo-papermod'
canonifyURLs = true

[params]
    env = 'production'
    title = 'some random docs'
    description = 'A simple thingy about docs'
    author = 'UrbanDaveBE'
    defaultTheme = 'light'
    showReadingTime = true
    showShareButtons = true
    showPostNavLinks = true
    ShowBreadCrumbs = true
    ShowCodeCopyButtons = true
    disableScrollToTop = false

    [params.homeInfoParams]
        Title = "Welcome to my Wissensdatenbank"
        Content = "Here I collect notes, guides, and architecture principles."

[[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '/'
    weight = 10

[[menu.main]]
    identifier = 'posts'
    name = 'Posts'
    url = '/posts/'
    weight = 20

[[menu.main]]
    identifier = 'about'
    name = 'About'
    url = '/about/'
    weight = 30
